
filegroup(
  name = "libdisparity_dnn_module.so_release", 
  srcs = ["libdisparity_dnn_module.so"],
  visibility = ["//visibility:public"],
)
 
filegroup(
  name = "libutils_module.so_release", 
  srcs = ["libutils_module.so"],
  visibility = ["//visibility:public"],
)
 
filegroup(
  name = "libcoarse_to_fine_module.so_release", 
  srcs = ["libcoarse_to_fine_module.so"],
  visibility = ["//visibility:public"],
)
 