
filegroup(
  name = "libserial_bmi160_module.so_release", 
  srcs = ["libserial_bmi160_module.so"],
  visibility = ["//visibility:public"],
)
 
filegroup(
  name = "libvicon_module.so_release", 
  srcs = ["libvicon_module.so"],
  visibility = ["//visibility:public"],
)
 
filegroup(
  name = "libv4l2_camera_module.so_release", 
  srcs = ["libv4l2_camera_module.so"],
  visibility = ["//visibility:public"],
)
 
filegroup(
  name = "libjoystick_module.so_release", 
  srcs = ["libjoystick_module.so"],
  visibility = ["//visibility:public"],
)
 