
filegroup(
  name = "libg_mapping_module.so_release", 
  srcs = ["libg_mapping_module.so"],
  visibility = ["//visibility:public"],
)
 
filegroup(
  name = "libcartographer_module.so_release", 
  srcs = ["libcartographer_module.so"],
  visibility = ["//visibility:public"],
)
 