
filegroup(
  name = "libapril_tags_module.so_release", 
  srcs = ["libapril_tags_module.so"],
  visibility = ["//visibility:public"],
)
 
filegroup(
  name = "libperception_module.so_release", 
  srcs = ["libperception_module.so"],
  visibility = ["//visibility:public"],
)
 
filegroup(
  name = "libstereo_visual_odometry_module.so_release", 
  srcs = ["libstereo_visual_odometry_module.so"],
  visibility = ["//visibility:public"],
)
 